window[mtsdk.globalName]('set', 'websiteId', '3eae6939-062b-4a51-a254-53652209305a');
window[mtsdk.globalName]('set', 'country', 'tz');
window[mtsdk.globalName]('set', 'revision', 1595599286);
window[mtsdk.globalName]('set', 'device', 'desktop');
window[mtsdk.globalName]('set', 'pageview', 2);
window[mtsdk.globalName]('set', 'send_ga', 1);
window[mtsdk.globalName]('loadPushNotification', '//assets.mxapis.com/js/push-004fc1ff5a.js', '//assets.mxapis.com/css/push-78d4219a7b.css', {"data":{"id":"3eae6939-062b-4a51-a254-53652209305a","domain":"localbitcoins.com","prompts":[{"id":"0e399005-f718-4c94-a923-f8656021b073","websiteId":"3eae6939-062b-4a51-a254-53652209305a","name":"Default","type":"default","status":1,"body":{"name":"default","icon":{"src":"https:\/\/assets.mxapis.com\/img\/push\/default_192_192.png"}},"trigger":"auto","triggerId":null,"targeting":["firefox","edge","chrome"]}],"popup":{"body":{"text":"Click Allow to confirm push notifications. Get updates and offers by subscribing to push notifications."}},"welcomeNotification":[],"traitMapping":[{"id":null,"websiteId":null,"name":"Topics","field":"topics","type":"array","system":true},{"id":null,"websiteId":null,"name":"Email","field":"email","type":"string","system":true},{"id":null,"websiteId":null,"name":"Phone","field":"phone","type":"string","system":true},{"id":null,"websiteId":null,"name":"First Name","field":"firstName","type":"string","system":true},{"id":null,"websiteId":null,"name":"Last Name","field":"lastName","type":"string","system":true},{"id":null,"websiteId":null,"name":"Email Opt In","field":"emailOptIn","type":"boolean","system":true},{"id":null,"websiteId":null,"name":"Web Push Opt In","field":"webPushOptIn","type":"boolean","system":true}],"safari_website_url":"","automation_on":false,"safari_web_id":"","config":{"data":{"gcm_project_number":null,"vapid_key":"BBYlwqwG_ywa_4jzMcLYMM9SVFToseVdFyciL9Mun-jSD1qHHomHltoLLy9XwkqKCy91qc8Xxakg_Nugozmdyl4","opt_in_enabled":true,"opt_in_type":"auto","button_shape":"circle","background_color":"#e34b4d","icon_color":"#ffffff","badge_background_color":"#000000","badge_text_color":"#ffffff","tooltip_background_color":"#000000","tooltip_color":"#ffffff","blocked_tooltip":"You have blocked notifications","subscribe_tooltip":"Subscribe to notifications","backdrop_color":"rgba(0,0,0,0.25)","info_background_color":"#ffffff","info_color":"#41090a","info_title":"Unblock Notifications","info_text":"Follow these instructions to allow notifications:","blocked_state_enabled":false,"blocked_button_position":"bottom_left","https_enabled":true,"http_domain":null}},"userConfig":{"data":{"push_branding":false}}}});
window[mtsdk.globalName]('setVisit');
window[mtsdk.globalName]('initCampaigns', '[]');
